import type { Metadata } from "next";
import "@/styles/globals.css";
import Providers from "@/providers/Providers";
import AuthHeader from "@/components/AuthHeader";
import { getUser } from "@/actions/auth/user.action";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser({ serverComponent: true });

  return (
    <html lang="ko">
      <body>
        <Providers>
          <AuthHeader user={user} />
          {children}
        </Providers>
      </body>
    </html>
  );
}
